### ISSUE TITLE
Elasticsearch wont run neither generating logs  

### ISSUE THREAD

**Issue by TheSidd** [josh-thurston/easyELK#2]
Complete technicsl details along with configure [Has been raised on elastic forum](https://discuss.elastic.co/t/failed-to-connect-to-localhost-port-9200-connection-refused-fresh-install/212788) but still no solution

**Comment by TheSidd** [comment]
```
 Enabling Services for Start on Boot
 Starting Elastic, Logstash, Kibana Services
Failed to enable unit: Unit file logstash.service does not exist.
Failed to enable unit: Unit file kibana.service does not exist.
Failed to start logstash.service: Unit logstash.service not found.
Failed to start kibana.service: Unit kibana.service not found.
 Service Status:
grep: elasticsearch(?!-)\b: No such file or directory
elasticsearch Not Running
grep: logstash(?!-)\b: No such file or directory
logstash Not Running
grep: kibana(?!-)\b: No such file or directory
kibana Not Running
 Wed Dec 25 11:54:52 IST 2019
 Finished easyELK Installer
 Your Turn: Finish Configuration
```

This is the error I got while installing.

**Comment by josh-thurston** [comment]
Hi @TheSidd sorry for the delay to respond due to holidays.  
easyELK was not created to run on Raspberry Pi. It only works on Linux Debian (Ubuntu) OS with chipset like Intel or AMD. I didn't want to create it for Raspberry Pi because a full ELK stack would require more processing power and memory than a Raspberry Pi can provide.  I didn't see the value in researching and creating new packages with an install script for ARM.  It is a lot of work and not enough return on the time investment.

I did see the value in getting data from my Raspberry Pi's, so I created easyBeats for Raspberry Pi so that you can collect data and ship it to ELK.  

Hope that helps clear things up

**Comment by swipswaps** [comment]
This helped me, thanks Josh! Will try on Pi . . .

//reference
```
root@mx:/home/owner/Downloads/easyELK# ./easyELK
 . . .
grep: elasticsearch(?!-)\b: No such file or directory
 . . .
```
//system
Linux mx 4.19.0-1-amd64 #1 SMP Debian 4.19.5-2~mx17+1 (2018-12-12) x86_64 GNU/Linux
